"""Deploy application files and user launchers without touching desktop settings."""
from dataclasses import dataclass
import json
from pathlib import Path
import os
import shlex
import shutil
import tempfile


@dataclass(frozen=True)
class InstallPaths:
    application: Path
    executable: Path
    integration: Path

    @classmethod
    def for_user(cls):
        home = Path.home()
        data = Path(os.environ.get('XDG_DATA_HOME', home / '.local/share'))
        config = Path(os.environ.get('XDG_CONFIG_HOME', home / '.config'))
        if not data.is_absolute() or not config.is_absolute():
            raise ValueError('XDG_DATA_HOME and XDG_CONFIG_HOME must be absolute paths.')
        return cls(data / 'orbit', home / '.local/bin/orbit', config / 'orbit/integration')


def write_atomic(path, content, executable=False):
    path.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary = tempfile.mkstemp(prefix='.orbit-', dir=path.parent)
    try:
        with os.fdopen(descriptor, 'w') as stream:
            stream.write(content)
        os.chmod(temporary, 0o755 if executable else 0o644)
        os.replace(temporary, path)
    finally:
        if os.path.exists(temporary):
            os.unlink(temporary)


def deploy(source, paths, python):
    target = paths.application
    if (source.resolve().is_relative_to(target.resolve())
            or target.resolve().is_relative_to(source.resolve())):
        raise ValueError('The install directory must be separate from the source checkout.')
    if target.is_symlink():
        raise ValueError(f'Refusing to replace a symlinked install directory: {target}')
    if target.exists() and not (target / '.orbit-install').is_file():
        raise ValueError(f'Refusing to replace an unmanaged directory: {target}')
    if paths.executable.exists() or paths.executable.is_symlink():
        if paths.executable.is_symlink() or '# Orbit managed launcher' not in paths.executable.read_text():
            raise ValueError(f'Refusing to replace an unrelated launcher: {paths.executable}')
    # Stage a complete runtime before replacing a previous managed installation.
    target.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.TemporaryDirectory(prefix='.orbit-stage-', dir=target.parent) as staging:
        stage = Path(staging) / 'application'
        stage.mkdir()
        for directory in ('orbit', 'bin', 'config'):
            shutil.copytree(source / directory, stage / directory,
                            ignore=shutil.ignore_patterns('__pycache__', '*.pyc'))
        shutil.copytree(source / 'assets/icons', stage / 'assets/icons')
        for name in ('LICENSE', 'VERSION'):
            shutil.copy2(source / name, stage / name)
        (stage / '.orbit-install').write_text('Orbit user installation\n')
        backup = Path(staging) / 'previous'
        if target.exists():
            target.rename(backup)
        try:
            stage.rename(target)
        except OSError:
            if backup.exists():
                backup.rename(target)
            raise
    root = shlex.quote(str(target))
    launcher = ('#!/bin/sh\n# Orbit managed launcher\n'
                f'export PYTHONPATH={root}${{PYTHONPATH:+:$PYTHONPATH}}\n'
                f'exec {shlex.quote(str(python))} -m orbit "$@"\n')
    write_atomic(paths.executable, launcher, executable=True)
    command = shlex.quote(str(paths.executable))
    # Quotes protect paths containing spaces in the compositor's command dispatcher.
    hyprlang = (source / 'config/hyprland.conf').read_text()
    hyprlang = hyprlang.replace('# Add: source = $HOME/Projects/Orbit/config/hyprland.conf',
                               '# Generated by Orbit install.sh; source this integration file.')
    hyprlang = hyprlang.replace('$orbit = $HOME/Projects/Orbit/bin/orbit', f'$orbit = {command}')
    lua = (source / 'config/hyprland.lua').read_text()
    lua = lua.replace("local orbit = os.getenv('HOME') .. '/Projects/Orbit/bin/orbit'",
                      f'local orbit = {json.dumps(command)}')
    lua = '\n'.join(lua.splitlines()[3:]) + '\n'
    write_atomic(paths.integration / 'hyprland.conf', hyprlang)
    write_atomic(paths.integration / 'hyprland.lua', lua)
